#!/usr/bin/perl -l
my %nickname = (
    Rossi => 'The Doctor',
    Stoner => 'Stacey Moaner',
    Doohan => 'Mad Mick',
    Iannone => 'The Maniac',
    Spencer => 'Fast Freddie',
    Edwards => 'Texas Tornado',
    Capirossi => 'Capirex',
    Biaggi => 'Mad Max',
    Lorenzo => 'JLo',
    Dovizioso => 'Desmodovi',
    Hayden => 'Kentucky Kid',
    Simoncelli => 'Sic',
    Crutchlow => 'The Dog',
    Marquez => 'Bimbominchia',
);

$nick = $nickname{shift()} and print $nick;
