#!/usr/bin/perl -l

if ($ARGV[0] eq '-h') {
    print <<EOF;
Usage: nick <rider>
Print nickname of MotoGP rider
EOF
    exit 0;
}

my %nickname = (
    Rossi => 'The Doctor',
    Stoner => 'Stacey Moaner',
    Doohan => 'Mad Mick',
    Iannone => 'The Maniac',
    Spencer => 'Fast Freddie',
    Edwards => 'Texas Tornado',
    Capirossi => 'Capirex',
    Biaggi => 'Mad Max',
    Lorenzo => 'JLo',
    Dovizioso => 'Desmodovi',
    Hayden => 'Kentucky Kid',
    Simoncelli => 'Sic',
    Crutchlow => 'The Dog',
    Marquez => 'Bimbominchia',
);

my $rider = shift;
$nick = $nickname{$rider} and print $nick;
